image:
  repository: baothaihcmut/ecommerce-api-gateway
  tag: v1.0.5
  pullPolicy: Always
configMap:
  name: server
  data:
    SERVER_PORT: "8080"
    AUTH_SERVICE_URI: "http://ecommerce-users-service-users-users-service-svc.ecommerce-app.svc.cluster.local:80"
    USERS_SERVICE_URI: "http://ecommerce-users-service-users-users-service-svc.ecommerce-app.svc.cluster.local:80"

config:
  from: "env"
  envConfigMap:
    - "server"
service:
  name: "api-gateway"
  type: ClusterIP
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 8080
resources:
  requests:
    cpu: "0.25"
    memory: "128Mi"
  limits:
    cpu: "0.5"
    memory: "256Mi"
serviceAccount:
  enabled: true
  name: wait-dependency
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]


initContainers: []
ingress:
  name: api-gateway
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.global-static-ip-name: ecommerce-app-ingress
    networking.gke.io/managed-certificates: ecommerce-managed-cert
  rules:
    - host: ecommerce-app.spsohcmut.xyz
      path: /
      service: api-gateway
      port: 80
      # tls: true
      # tlsSecret: ecommerce-cert

# gkeCerts:
#   enabled: true
#   name: ecommerce-cert
#   domains:
#     - "ecommerce-app.spsohcmut.xyz"

