server:
  port: 8083
spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb+srv://thaibao22042k4:22042004bao@ecommerce-go.xbph8.mongodb.net/productdb?retryWrites=true&w=majority&appName=ecommerce-go
      


aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    bucket: ecommerce-app-product-bucket 