server:
  port: ${SERVER_PORT:8083}
grpc:
  client:
    shops-service:
      address: "static://localhost:9094"
      negotiationType: plaintext


spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGO_URI:mongo://localhost:27017}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
  #   producer:
  #     key-serializer: org.apache.kafka.common.serialization.StringSerializer
  #     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      


aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    bucket: ecommerce-app-product-bucket 

services:
  address:
    shop-service: "localhost:8084"
