server:
  port: ${SERVER_PORT:8081}
grpc:
  server:
    port: ${GRPC_PORT:9091}


spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      enabled: "true"
      uri: ${MONGO_URI:mongo://localhost:27017}
      database: "productdb"
      connection-pool:
        max-connection: 10
        min-connection: 2
        max-connection-idle-time: 5
      


aws:
  s3:
    enabled: "true"
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    bucket: ecommerce-app-product-bucket 

