server:
  port: 8762

spring:
  main: 
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
jwt:
  secret: "your_accesstoken_key111111111111111111111"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761
