server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api/v1}  # Use a variable to allow dynamic context path configuration

spring:
  main: 
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      prefix: ${API_PREFIX:${server.servlet.context-path}}  
      open-apis:
        - "${server.servlet.context-path}/auth/log-in" 
        - "${server.servlet.context-path}/auth/sign-up"
      routes:
        auth-service: ${AUTH_SERVICE_URI:http://localhost:8083}
        users-service: ${USER_SERVICE_URI:http://localhost:8083}
        shops-service: ${SHOP_SERVICE_URI:http://localhost:8082}

springdoc:
  api-docs:
    path: "${server.servlet.context-path}/api-docs"  # Dynamically use context-path
  swagger-ui:
    path: "${server.servlet.context-path}/swagger-ui.html"  # Dynamically use context-path
    urls:
      - name: "Shops service"
        url: "${server.servlet.context-path}/shops-service/api-docs"  # Use context-path for API docs
      - name: "Users service"
        url: "${server.servlet.context-path}/users-service/api-docs"  # Use context-path for API docs

jwt:
  secret: "your_accesstoken_key111111111111111111111"
