server:
  port: ${SERVER_POT:8672}

spring:
  main: 
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=${APP_PREFIX_COUNT:2}
        - name: AuthFilter
          args:
            openApiEndpoints:
              - "/auth/sign-up"
              - "/auth/log-in"
            prefix: ${APP_PREFIX:/api/v1}
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://localhost:8081}
          predicates:
            - Path=${APP_PREFIX:/api/v1}/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: authServiceCircuitBreaker
                fallbackUri: forward:/fallback/auth
        - id: product-service
          uri: ${PRODUCT_SERVICE_URI:http://localhost:8083}
          predicates:
            - Path=${APP_PREFIX:/api/v1}/product/**
jwt:
  secret: "your_accesstoken_key111111111111111111111"


