image:
  repository: baothaihcmut/ecommerce-mail-service
  tag: v1
  pullPolicy: Always
configMap:
  name: main
  data:
    SERVER_PORT: "8080"
    RABBITMQ_URI: "amqps://nvfpayhh:X7H1EaS5XkBgNAxG9oa2FhrsDT6SVkho@possum.lmq.cloudamqp.com/nvfpayhh"

config:
  from: "env"
  envConfigMap:
    - "main"
service:
  name: "mail-service"
  type: ClusterIP
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 8080
resources:
  requests:
    cpu: "0.2"
    memory: "128Mi"
  limits:
    cpu: "0.4"
    memory: "256Mi"
serviceAccount:
  enabled: true
  name: wait-dependency
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]

initContainers: []
  # - name: wait-for-dependencies
  #   image: bitnami/kubectl:latest
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       echo "Waiting for Redis and Kafka to be ready..."
  #       kubectl wait --for=condition=Ready pod -l app=ecommerce-app-dependency --timeout=300s






