server:
  port: ${SERVER_PORT:8084}
grpc:
  server:
    port: ${GRPC_PORT:9094}  
    reflection-service-enabled: true  
    security:
      enabled: false
  client:
    products-service:
      address: ${PRODUCTS_SERVICE_URI:static://localhost:9093}
      negotiationType: plaintext
spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: mongodb+srv://thaibao22042k4:22042004bao@ecommerce-go.xbph8.mongodb.net/productdb?retryWrites=true&w=majority&appName=ecommerce-go
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      consumer-group-id: "shops-service"
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    bucket: ecommerce-app-product-bucket
