server:
  port: ${SERVER_PORT:8082}
grpc:
  server:
    port: ${GRPC_PORT:9094}  
    reflection-service-enabled: true  
    security:
      enabled: false
  client:
    products-service:
      address: ${PRODUCTS_SERVICE_URI:static://localhost:9093}
      negotiationType: plaintext
    users-service:
      address: ${USERS_SERVICE_URI:static://localhost:9095}
      negotiationType: plaintext
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      uri: ${MONGO_URI:mongo://localhost:27017}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    consumer:
      consumer-group-id: "shops-service"
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    bucket: ecommerce-app-product-bucket
