server:
  port: ${SERVER_PORT:8086}
grpc:
  server:
    port: ${GRPC_PORT:18086}
    reflection-service-enabled: true  
    security:
      enabled: false
  client:
    products-service:
      address: ${PRODUCTS_SERVICE_URI:static://localhost:9093}
      negotiationType: plaintext
    users-service:
      address: ${USERS_SERVICE_URI:static://localhost:9095}
      negotiationType: plaintext
springdoc:
  info:
    title: "Shops service"
    description: "Shops service"
    version: "v1.0.0"
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    mongodb:
      enabled: "true"
      uri: ${MONGO_URI:mongo://localhost:27017}
      database: "shopdb"
      connection-pool:
        max-connection: 10
        min-connection: 2
        max-connection-idle-time: 5
  
aws:
  s3:
    enabled: "true"
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: us-east-1
    bucket: ecommerce-app-product-bucket
dependencies:
  mongo:
    enabled: true
  s3:
    enabled: true
