image:
  repository: baothaihcmut/ecommerce-users-service
  tag: v1.0.4
  pullPolicy: Always
configMap:
  name: main
  data:
    SERVER_PORT: "8080"
    RABBITMQ_URI: "amqps://nvfpayhh:X7H1EaS5XkBgNAxG9oa2FhrsDT6SVkho@possum.lmq.cloudamqp.com/nvfpayhh"
    REDIS_HOST: "ecommerce-redis-master.ecommerce-app.svc.cluster.local"
    REDIS_PORT: "6379"
    REDIS_PASSWORD: "redispassword"
    REDIS_USERNAME: "default"

config:
  from: "env"
  envConfigMap:
    - "main"
service:
  name: "users-service"
  type: ClusterIP
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 8080
resources:
  requests:
    cpu: "0.3"
    memory: "200Mi"
  limits:
    cpu: "0.6"
    memory: "400Mi"
serviceAccount:
  enabled: true
  name: wait-dependency
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]

initContainers: []
  # - name: wait-for-dependencies
  #   image: bitnami/kubectl:latest
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       echo "Waiting for Redis and Kafka to be ready..."
  #       kubectl wait --for=condition=Ready pod -l app=ecommerce-app-dependency --timeout=300s






