image:
  repository: baothaihcmut/ecommerce-users-service
  tag: v1
  pullPolicy: Always
configMap:
  name: main
  data:
    SERVER_PORT: "8080"
    RABBITMQ_HOST: "ecommerce-rabbitmq.ecommerce-app.svc.cluster.local"
    RABBITMQ_PORT: "5672"
    RABBITMQ_USERNAME: "rabbimq_user"
    RABBITMQ_PASSWORD: "rabbitmq_password"
    RABBITMQ_VHOST: "ecommerce-vhost"
    REDIS_HOST: "ecommerce-app-redis-master.ecommerce-app.svc.cluster.local"
    REDIS_PORT: "6379"

config:
  from: "env"
  envConfigMap:
    - "main"
service:
  name: "users-service"
  type: ClusterIP
  ports:
    - name: "http"
      protocol: "TCP"
      port: 80
      targetPort: 8080
resources:
  requests:
    cpu: "0.1"
    memory: "128Mi"
  limits:
    cpu: "0.2"
    memory: "256Mi"
serviceAccount:
  enabled: true
  name: wait-dependency
  rules:
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["get", "list", "watch"]

initContainers: []
  # - name: wait-for-dependencies
  #   image: bitnami/kubectl:latest
  #   command:
  #     - /bin/sh
  #     - -c
  #     - |
  #       echo "Waiting for Redis and Kafka to be ready..."
  #       kubectl wait --for=condition=Ready pod -l app=ecommerce-app-dependency --timeout=300s






