server:
  port: ${SERVER_PORT:8082}
spring:
  mail:
    enabled: "true"
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER:banbao22042004@gmail.com}
    password: ${MAIL_PASSWORD:nvnj ejjh fkam cqll}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    enabled: "true"
    uri: ${RABBITMQ_URI:amqps://nvfpayhh:X7H1EaS5XkBgNAxG9oa2FhrsDT6SVkho@possum.lmq.cloudamqp.com/nvfpayhh}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/}
    concurrentConsumers: 5
dependencies:
  rabbitmq:
    enabled: true
  mailer:
    enabled: true

    


      
