server:
  port: ${SERVER_PORT:8083}
grpc:
  server:
    port: ${GRPC_PORT:9095}  
    reflection-service-enabled: true  
    security:
      enabled: false
spring:
  application:
    name: users
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-tight-glitter-a17vbx2k-pooler.ap-southeast-1.aws.neon.tech/ecommerce-go-users?sslmode=require}
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_ARFzU8NZupg7}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  
    show-sql: true
  data:
    redis:
      host: ${REDIST_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: "" 
      database: 0
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VHOST:/ecommerce-app}


jwt:
  access_token:
    secret: your_accesstoken_key111111111111111111111
    expiry: 3
  refresh_token:
    secret: your_accesstoken_key111111111111111111111
    expiry: 7
