server:
  port: ${SERVER_PORT:8085}
grpc:
  server:
    port: ${GRPC_PORT:18085}  
    reflection-service-enabled: true  
    security:
      enabled: false
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: users
  datasource:
    enabled: "true"
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    connection-pool:
      max-connection: 10
      min-connection: 2
      max-connection-idle-time: 300000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  
    show-sql: true
  data:
    redis:
      enabled: "true"
      host: ${REDIS_HOST:redis-13770.c321.us-east-1-2.ec2.redns.redis-cloud.com}
      port: ${REDIS_PORT:13770}
      password: ${REDIS_PASSWORD:Tazqqr2OljF2IGBJQ5pkz8RAbbpSCGkN}
      username: ${REDIS_USERNAME:default} 
      database: 0
      connection-pool-size: ${REDIS_CONNECTION_POOL_SIZE:5}
      connection-minimun-idle-size: ${REDIS_CONNECTION_MINIMUM_IDLE_SIZE:2}
      idle-connection-timeout: 10000
  rabbitmq:
    enabled: "true"
    uri: ${RABBITMQ_URI}
    # host: ${RABBITMQ_HOST:localhost}
    # port: ${RABBITMQ_PORT:5672}
    # username: ${RABBITMQ_USERNAME:guest}
    # password: ${RABBITMQ_PASSWORD:guest}
    # virtual-host: ${RABBITMQ_VHOST:/}

springdoc:
  info:
    title: "Users service"
    description: "Users service"
    version: "v1.0.0"
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

jwt:
  access_token:
    secret: your_accesstoken_key111111111111111111111
    expiry: 3
  refresh_token:
    secret: your_accesstoken_key111111111111111111111
    expiry: 7
