additionalArguments:
  - "--certificatesresolvers.letsencrypt-prod.acme.email=thaibao22042k4@gmail.com"
  - "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
  - "--certificatesresolvers.letsencrypt-prod.acme.httpchallenge.entrypoint=web"
persistence:
  enabled: true
  path: /data
ports:
  web:
    port: 80
    exposed: true  # Changed from 'expose' to 'exposed'
    expose:  # Define as an object if needed by your chart version
      default: true
  websecure:
    port: 443
    exposed: true  # Changed from 'expose' to 'exposed'
    expose:  # Define as an object if needed
      default: true
providers:
  kubernetesCRD:
    enabled: true
logs:
  general:
    level: DEBUG