architecture: standalone
auth:
  enabled: true
  password: "redispassword"
master:
  persistence:
    storageClass: "local-path"
    size: "500Mi"
resources:
  requests:
    cpu: "0.1"
    memory: "125Mi"
  limits:
    cpu: "0.2"
    memory: "250Mi"
