listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT
  interbroker:
    protocol: PLAINTEXT
controller:
  replicaCount: 1
  resources:
    requests:
      cpu: "0.1"
      memory: "125Mi"
    limits:
      cpu: "0.2"
      memory: "250Mi"
  persistence:
    storageClass: "local-path"
broker:
  replicaCount: 1
  extraConfig: |
    offsets.topic.replication.factor = 1
    auto.create.topics.enable = true
  resources:
    requests:
      cpu: "0.1"
      memory: "250Mi"
    limits:
      cpu: "0.2"
      memory: "500Mi"
  persistence:
    storageClass: "local-path"
kraft:
  enabled: true
  metadataLogDir: /bitnami/kafka/data/meta
  autoCreateTopicsEnable: true
  clusterId: "185040142880-e0o5rn2ms0d01vclb7oun"
