server:
  port: ${SERVER_PORT:8082}
grpc:
  server:
    port: ${GRPC_PORT:18082}
  client:
    products-service:
      address: ${PRODUCTS_SERVICE_URI:static://localhost:18081}
      negotiationType: plaintext
    payment-service:
      address: ${PAYMENT_SERVICE_URI:static://localhost:18084}
      negotiationType: plaintext
    users-service:
      address: ${USERS_SERVICE_URI:static://localhost:18085}
      negotiationType: plaintext



spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    enabled: "true"
    url: ${DB_URL:jdbc:postgresql://ep-tight-glitter-a17vbx2k-pooler.ap-southeast-1.aws.neon.tech/ecommerce-go-users?sslmode=require}
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_ARFzU8NZupg7}
    driver-class-name: org.postgresql.Driver
    connection-pool:
      max-connection: 10
      min-connection: 2
      max-connection-idle-time: 300000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  
    show-sql: true
  rabbitmq:
    enabled: "true"
    uri: ${RABBITMQ_URI}
    
  